<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateModelsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('models', function (Blueprint $table) {
            $table->id();
            $table->timestamps();
            $table->string('model');
            $table->unsignedBigInteger('fk_brand');
            $table->string('year')->nullable();
            $table->foreign('fk_brand')->references('id')->on('brands');
;        });

        DB::table('models')->insert(
            array(
                ['model'=> '', 'fk_brand' => 1],
                ['model'=> 'CRX', 'fk_brand' => 1],
                ['model'=> 'GT', 'fk_brand' => 1],
                ['model'=> 'GT-2', 'fk_brand' => 1],
                ['model'=> 'GTL', 'fk_brand' => 1],
                ['model'=> 'GTM', 'fk_brand' => 1],
                ['model'=> 'GTM C2', 'fk_brand' => 1],
                ['model'=> 'Marruá', 'fk_brand' => 2],
                ['model'=> 'GT 1.8 Street', 'fk_brand' => 3],
                ['model'=> 'Spyder', 'fk_brand' => 3],
                ['model'=> 'Alfa Romeo 2000', 'fk_brand' => 4],
                ['model'=> '2300', 'fk_brand' => 4],
                ['model'=> '2300 Ex', 'fk_brand' => 4],
                ['model'=> '2300 B', 'fk_brand' => 4],
                ['model'=> '2300 Ti', 'fk_brand' => 4],
                ['model'=> '2300 Rio', 'fk_brand' => 4],
                ['model'=> '2300 SL', 'fk_brand' => 4],
                ['model'=> '2300 Ti 4', 'fk_brand' => 4],
                ['model'=> '2300 Álcool Ti', 'fk_brand' => 4],
                ['model'=> '145', 'fk_brand' => 4],
                ['model'=> '155', 'fk_brand' => 4],
                ['model'=> '164', 'fk_brand' => 4],
                ['model'=> '156', 'fk_brand' => 4],
                ['model'=> '147', 'fk_brand' => 4],
                ['model'=> '166', 'fk_brand' => 4],
                ['model'=> 'GTV & Spider', 'fk_brand' => 4],
                ['model'=> 'XKCoupe 2007', 'fk_brand' => 5],
                ['model'=> 'XK120 2007', 'fk_brand' => 5],
                ['model'=> 'Cobra 2002', 'fk_brand' => 5],
                ['model'=> 'GT40', 'fk_brand' => 5],
                ['model'=> 'A 11 Avallone', 'fk_brand' => 6],
                ['model'=> 'TF 6R', 'fk_brand' => 6],
                ['model'=> 'Fusca Cabriolet', 'fk_brand' => 6],
                ['model'=> 'Limosine Monza', 'fk_brand' => 6],
                ['model'=> 'A 52', 'fk_brand' => 6],
                ['model'=> 'Avallone Presidencial', 'fk_brand' => 6],
                ['model'=> 'A3', 'fk_brand' => 7],
                ['model'=> 'A3 Sedan', 'fk_brand' => 7],
                ['model'=> 'Q3', 'fk_brand' => 7],
                ['model'=> 'TT', 'fk_brand' => 7],
                ['model'=> 'A1', 'fk_brand' => 7],
                ['model'=> 'R8', 'fk_brand' => 7],
                ['model'=> 'A4', 'fk_brand' => 7],
                ['model'=> 'A5', 'fk_brand' => 7],
                ['model'=> 'A6', 'fk_brand' => 7],
                ['model'=> 'A7', 'fk_brand' => 7],
                ['model'=> 'Q5', 'fk_brand' => 7],
                ['model'=> 'Q7', 'fk_brand' => 7],
                ['model'=> 'Senna', 'fk_brand' => 7],
                ['model'=> '122 C', 'fk_brand' => 8],
                ['model'=> 'Bianco S', 'fk_brand' => 9],
                ['model'=> 'Bianco Série', 'fk_brand' => 9],
                ['model'=> 'Bianco Tarpan', 'fk_brand' => 9],
                ['model'=> 'Bianco Tarpan TS', 'fk_brand' => 9],
                ['model'=> 'Série 1', 'fk_brand' => 10],
                ['model'=> 'Série 3', 'fk_brand' => 10],
                ['model'=> 'X1', 'fk_brand' => 10],
                ['model'=> 'X3', 'fk_brand' => 10],
                ['model'=> 'X4', 'fk_brand' => 10],
                ['model'=> 'Z3', 'fk_brand' => 10],
                ['model'=> 'Z4', 'fk_brand' => 10],
                ['model'=> 'Série 2', 'fk_brand' => 10],
                ['model'=> 'Série 4', 'fk_brand' => 10],
                ['model'=> 'Série 5', 'fk_brand' => 10],
                ['model'=> 'Série 7', 'fk_brand' => 10],
                ['model'=> 'Série 8', 'fk_brand' => 10],
                ['model'=> 'X2', 'fk_brand' => 10],
                ['model'=> 'X5', 'fk_brand' => 10],
                ['model'=> 'X6', 'fk_brand' => 10],
                ['model'=> 'M2 Competition', 'fk_brand' => 10],
                ['model'=> 'M3 Sedã', 'fk_brand' => 10],
                ['model'=> 'M4 Coupé', 'fk_brand' => 10],
                ['model'=> 'M5', 'fk_brand' => 10],
                ['model'=> 'X6M', 'fk_brand' => 10],
                ['model'=> 'i3', 'fk_brand' => 10],
                ['model'=> 'Fera XK', 'fk_brand' => 11],
                ['model'=> '4200 GT', 'fk_brand' => 12],
                ['model'=> '4200 GTS', 'fk_brand' => 12],
                ['model'=> 'Super 90', 'fk_brand' => 13],
                ['model'=> 'Spyder 550', 'fk_brand' => 13],
                ['model'=> '911 Carrera', 'fk_brand' => 13],
                ['model'=> '911 Carrera 2/4', 'fk_brand' => 13],
                ['model'=> '911 Carrera conversível', 'fk_brand' => 13],
                ['model'=> 'MG MGA', 'fk_brand' => 13],
                ['model'=> 'EJ 1', 'fk_brand' => 13],
                ['model'=> 'Formigão', 'fk_brand' => 13],
                ['model'=> 'CBT Javali 4x2', 'fk_brand' => 14],
                ['model'=> 'CBT Javali 4x4', 'fk_brand' => 14],
                ['model'=> 'CBT Javali 4x4 (turbo)', 'fk_brand' => 14],
                ['model'=> 'Roadster 356', 'fk_brand' => 15],
                ['model'=> 'Speedster 356', 'fk_brand' => 15],
                ['model'=> 'Spyder 550 R', 'fk_brand' => 15],
                ['model'=> 'Spyder 550 S', 'fk_brand' => 15],
                ['model'=> 'Spyder 550 S L.M.', 'fk_brand' => 15],
                ['model'=> 'Super 90', 'fk_brand' => 15],
                ['model'=> 'Arrizzo 5', 'fk_brand' => 16],
                ['model'=> 'Celer', 'fk_brand' => 16],
                ['model'=> 'QQ', 'fk_brand' => 16],
                ['model'=> 'Tiggo 2', 'fk_brand' => 16],
                ['model'=> 'Tiggo 7', 'fk_brand' => 16],
                ['model'=> 'Face', 'fk_brand' => 16],
                ['model'=> 'Cielo', 'fk_brand' => 16],
                ['model'=> 'Arrizo 5E', 'fk_brand' => 16],
                ['model'=> '3100/Brasil', 'fk_brand' => 17],
                ['model'=> 'A-10', 'fk_brand' => 17],
                ['model'=> 'A-20', 'fk_brand' => 17],
                ['model'=> 'Alvorada', 'fk_brand' => 17],
                ['model'=> 'Amazona', 'fk_brand' => 17],
                ['model'=> 'Astra', 'fk_brand' => 17],
                ['model'=> 'Beretta', 'fk_brand' => 17],
                ['model'=> 'Blazer', 'fk_brand' => 17],
                ['model'=> 'Bonanza', 'fk_brand' => 17],
                ['model'=> 'Bolt', 'fk_brand' => 17],
                ['model'=> 'C-10', 'fk_brand' => 17],
                ['model'=> 'C-14', 'fk_brand' => 17],
                ['model'=> 'C-1416', 'fk_brand' => 17],
                ['model'=> 'C-15', 'fk_brand' => 17],
                ['model'=> 'C-20', 'fk_brand' => 17],
                ['model'=> 'Camaro', 'fk_brand' => 17],
                ['model'=> 'Caravan', 'fk_brand' => 17],
                ['model'=> 'Celta', 'fk_brand' => 17],
                ['model'=> 'Chevette Hatch', 'fk_brand' => 17],
                ['model'=> 'Chevette', 'fk_brand' => 17],
                ['model'=> 'Chevette Junior', 'fk_brand' => 17],
                ['model'=> 'Chevy 500', 'fk_brand' => 17],
                ['model'=> 'Cobalt', 'fk_brand' => 17],
                ['model'=> 'Corisco', 'fk_brand' => 17],
                ['model'=> 'Corsa', 'fk_brand' => 17],
                ['model'=> 'Corsa Sedan / Classic', 'fk_brand' => 17],
                ['model'=> 'Corsa Pick-up', 'fk_brand' => 17],
                ['model'=> 'Corsa Wagon', 'fk_brand' => 17],
                ['model'=> 'Cruze', 'fk_brand' => 17],
                ['model'=> 'Cruze Sport6', 'fk_brand' => 17],
                ['model'=> 'D-10', 'fk_brand' => 17],
                ['model'=> 'D-20', 'fk_brand' => 17],
                ['model'=> 'Ipanema', 'fk_brand' => 17],
                ['model'=> 'Kadett', 'fk_brand' => 17],
                ['model'=> 'Kadett Conversível', 'fk_brand' => 17],
                ['model'=> 'Marajó', 'fk_brand' => 17],
                ['model'=> 'Meriva', 'fk_brand' => 17],
                ['model'=> 'Montana', 'fk_brand' => 17],
                ['model'=> 'Monza Sedan', 'fk_brand' => 17],
                ['model'=> 'Monza Hatch', 'fk_brand' => 17],
                ['model'=> 'Omega', 'fk_brand' => 17],
                ['model'=> 'Onix', 'fk_brand' => 17],
                ['model'=> 'Opala Coupé', 'fk_brand' => 17],
                ['model'=> 'Opala', 'fk_brand' => 17],
                ['model'=> 'Prisma', 'fk_brand' => 17],
                ['model'=> 'Silverado', 'fk_brand' => 17],
                ['model'=> 'S10', 'fk_brand' => 17],
                ['model'=> 'Spin', 'fk_brand' => 17],
                ['model'=> 'Suprema', 'fk_brand' => 17],
                ['model'=> 'TrailBlazer', 'fk_brand' => 17],
                ['model'=> 'Vectra', 'fk_brand' => 17],
                ['model'=> 'Vectra GT', 'fk_brand' => 17],
                ['model'=> 'Veraneio', 'fk_brand' => 17],
                ['model'=> 'Volt', 'fk_brand' => 17],
                ['model'=> 'Zafira', 'fk_brand' => 17],
                ['model'=> 'Equinox', 'fk_brand' => 17],
                ['model'=> 'SS10', 'fk_brand' => 17],
                ['model'=> 'Caprice', 'fk_brand' => 17],
                ['model'=> 'Malibu', 'fk_brand' => 17],
                ['model'=> '1800', 'fk_brand' => 18],
                ['model'=> 'Charger', 'fk_brand' => 18],
                ['model'=> 'Dakota', 'fk_brand' => 18],
                ['model'=> 'Dart Sedã', 'fk_brand' => 18],
                ['model'=> 'Dart Coupé', 'fk_brand' => 18],
                ['model'=> 'LeBaron', 'fk_brand' => 18],
                ['model'=> 'Magnum', 'fk_brand' => 18],
                ['model'=> 'Polara', 'fk_brand' => 18],
                ['model'=> 'Journey', 'fk_brand' => 18],
                ['model'=> 'Durango', 'fk_brand' => 18],
                ['model'=> 'Town & Country', 'fk_brand' => 18],
                ['model'=> '300', 'fk_brand' => 18],
                ['model'=> 'PT Cruiser', 'fk_brand' => 18],
                ['model'=> 'Caravan/Grand Caravan', 'fk_brand' => 18],
                ['model'=> 'Stratus', 'fk_brand' => 18],
                ['model'=> 'Aircross', 'fk_brand' => 19],
                ['model'=> 'C3', 'fk_brand' => 19],
                ['model'=> 'C4 Cactus', 'fk_brand' => 19],
                ['model'=> 'Xsara Picasso', 'fk_brand' => 19],
                ['model'=> 'DS3', 'fk_brand' => 19],
                ['model'=> 'Xantia', 'fk_brand' => 19],
                ['model'=> 'C5 2001', 'fk_brand' => 19],
                ['model'=> 'C4 Pallas', 'fk_brand' => 19],
                ['model'=> 'C4 Lounge', 'fk_brand' => 19],
                ['model'=> 'DS5', 'fk_brand' => 19],
                ['model'=> 'C3 Picasso', 'fk_brand' => 19],
                ['model'=> 'XM', 'fk_brand' => 19],
                ['model'=> 'ZX', 'fk_brand' => 19],
                ['model'=> 'Concorde ', 'fk_brand' => 20],
                ['model'=> 'Dardo F 1.3', 'fk_brand' => 21],
                ['model'=> 'Dardo F 1.5', 'fk_brand' => 21],
                ['model'=> 'CL-244', 'fk_brand' => 22],
                ['model'=> 'CL-330', 'fk_brand' => 22],
                ['model'=> 'Espero', 'fk_brand' => 23],
                ['model'=> 'Nubira', 'fk_brand' => 23],
                ['model'=> 'Lanos', 'fk_brand' => 23],
                ['model'=> 'Leganza', 'fk_brand' => 23],
                ['model'=> 'Super Salon', 'fk_brand' => 23],
                ['model'=> 'Tico', 'fk_brand' => 23],
                ['model'=> 'Prince', 'fk_brand' => 23],
                ['model'=> 'Cuore', 'fk_brand' => 24],
                ['model'=> 'Applause', 'fk_brand' => 24],
                ['model'=> 'Terios', 'fk_brand' => 24],
                ['model'=> 'Feroza', 'fk_brand' => 24],
                ['model'=> 'Squalo', 'fk_brand' => 25],
                ['model'=> 'Julia', 'fk_brand' => 25],
                ['model'=> 'Belcar', 'fk_brand' => 26],
                ['model'=> 'Caiçara', 'fk_brand' => 26],
                ['model'=> 'Camioneta', 'fk_brand' => 26],
                ['model'=> 'Candango', 'fk_brand' => 26],
                ['model'=> 'F-91 Universal', 'fk_brand' => 26],
                ['model'=> 'Fissore', 'fk_brand' => 26],
                ['model'=> 'Grande', 'fk_brand' => 26],
                ['model'=> 'Pracinha', 'fk_brand' => 26],
                ['model'=> 'Vemaguet', 'fk_brand' => 26],
                ['model'=> 'Rancho PK', 'fk_brand' => 27],
                ['model'=> 'Rancho TT ', 'fk_brand' => 27],
                ['model'=> 'GT e GT-R', 'fk_brand' => 27],
                ['model'=> 'Mog', 'fk_brand' => 27],
                ['model'=> 'Aris', 'fk_brand' => 27],
                ['model'=> 'Art', 'fk_brand' => 28],
                ['model'=> 'Topazzio', 'fk_brand' => 29],
                ['model'=> 'EE-12', 'fk_brand' => 30],
                ['model'=> 'EE-34', 'fk_brand' => 30],
                ['model'=> '4', 'fk_brand' => 30],
                ['model'=> 'Camper', 'fk_brand' => 31],
                ['model'=> 'Super 90', 'fk_brand' => 31],
                ['model'=> 'Super 90 Cabriolet', 'fk_brand' => 31],
                ['model'=> 'Envesa 4', 'fk_brand' => 32],
                ['model'=> 'Effa M100', 'fk_brand' => 33],
                ['model'=> 'ML-929', 'fk_brand' => 34],
                ['model'=> 'TS', 'fk_brand' => 35],
                ['model'=> 'Beta', 'fk_brand' => 35],
                ['model'=> 'Beta Cabriolet', 'fk_brand' => 35],
                ['model'=> 'Quadro', 'fk_brand' => 35],
                ['model'=> '147', 'fk_brand' => 36],
                ['model'=> 'Argo', 'fk_brand' => 36],
                ['model'=> 'Brava', 'fk_brand' => 36],
                ['model'=> 'Bravo', 'fk_brand' => 36],
                ['model'=> 'City', 'fk_brand' => 36],
                ['model'=> 'Cronos', 'fk_brand' => 36],
                ['model'=> 'Doblô', 'fk_brand' => 36],
                ['model'=> 'Ducato', 'fk_brand' => 36],
                ['model'=> 'Elba', 'fk_brand' => 36],
                ['model'=> 'Fiorino', 'fk_brand' => 36],
                ['model'=> 'Idea', 'fk_brand' => 36],
                ['model'=> 'Linea', 'fk_brand' => 36],
                ['model'=> 'Marea', 'fk_brand' => 36],
                ['model'=> 'Marea Weekend', 'fk_brand' => 36],
                ['model'=> 'Mobi', 'fk_brand' => 36],
                ['model'=> 'Oggi', 'fk_brand' => 36],
                ['model'=> 'Palio', 'fk_brand' => 36],
                ['model'=> 'Weekend/Palio Weekend', 'fk_brand' => 36],
                ['model'=> 'Panorama', 'fk_brand' => 36],
                ['model'=> 'Prêmio', 'fk_brand' => 36],
                ['model'=> 'Punto', 'fk_brand' => 36],
                ['model'=> 'Siena/Grand Siena', 'fk_brand' => 36],
                ['model'=> 'Spazio', 'fk_brand' => 36],
                ['model'=> 'Stilo', 'fk_brand' => 36],
                ['model'=> 'Strada', 'fk_brand' => 36],
                ['model'=> 'Tempra', 'fk_brand' => 36],
                ['model'=> 'Tipo', 'fk_brand' => 36],
                ['model'=> 'Toro', 'fk_brand' => 36],
                ['model'=> 'Uno/Mille', 'fk_brand' => 36],
                ['model'=> 'Coupé', 'fk_brand' => 36],
                ['model'=> '500', 'fk_brand' => 36],
                ['model'=> '2000 JK', 'fk_brand' => 37],
                ['model'=> '2150 JK', 'fk_brand' => 37],
                ['model'=> 'Onça', 'fk_brand' => 37],
                ['model'=> 'Fúria GT', 'fk_brand' => 37],
                ['model'=> 'Belina', 'fk_brand' => 38],
                ['model'=> 'Belina II', 'fk_brand' => 38],
                ['model'=> 'Corcel', 'fk_brand' => 38],
                ['model'=> 'Corcel II', 'fk_brand' => 38],
                ['model'=> 'Courier', 'fk_brand' => 38],
                ['model'=> 'Courier Van', 'fk_brand' => 38],
                ['model'=> 'Del Rey', 'fk_brand' => 38],
                ['model'=> 'Del Rey Scala', 'fk_brand' => 38],
                ['model'=> 'EcoSport', 'fk_brand' => 38],
                ['model'=> 'Escort', 'fk_brand' => 38],
                ['model'=> 'Escort SW', 'fk_brand' => 38],
                ['model'=> 'Escort conversível', 'fk_brand' => 38],
                ['model'=> 'F-100', 'fk_brand' => 38],
                ['model'=> 'F-1000', 'fk_brand' => 38],
                ['model'=> 'F-250', 'fk_brand' => 38],
                ['model'=> 'F-75', 'fk_brand' => 38],
                ['model'=> 'Fiesta', 'fk_brand' => 38],
                ['model'=> 'Focus', 'fk_brand' => 38],
                ['model'=> 'Jeep', 'fk_brand' => 38],
                ['model'=> 'Galaxie 500', 'fk_brand' => 38],
                ['model'=> 'Galaxie', 'fk_brand' => 38],
                ['model'=> 'Ka', 'fk_brand' => 38],
                ['model'=> 'Ka+', 'fk_brand' => 38],
                ['model'=> 'LTD', 'fk_brand' => 38],
                ['model'=> 'LTD Landau/Landau', 'fk_brand' => 38],
                ['model'=> 'Maverick', 'fk_brand' => 38],
                ['model'=> 'Mustang', 'fk_brand' => 38],
                ['model'=> 'Mondeo', 'fk_brand' => 38],
                ['model'=> 'Pampa', 'fk_brand' => 38],
                ['model'=> 'Ranger', 'fk_brand' => 38],
                ['model'=> 'Royale', 'fk_brand' => 38],
                ['model'=> 'Rural', 'fk_brand' => 38],
                ['model'=> 'Verona', 'fk_brand' => 38],
                ['model'=> 'Versailles', 'fk_brand' => 38],
                ['model'=> 'Fusion', 'fk_brand' => 38],
                ['model'=> 'Edge', 'fk_brand' => 38],
                ['model'=> 'Taurus', 'fk_brand' => 38],
                ['model'=> 'Crown Victoria', 'fk_brand' => 38],
                ['model'=> 'Furglaine', 'fk_brand' => 39],
                ['model'=> 'EC7', 'fk_brand' => 40],
                ['model'=> 'GC2', 'fk_brand' => 40],
                ['model'=> 'Cobra', 'fk_brand' => 41],
                ['model'=> '3500 HD', 'fk_brand' => 42],
                ['model'=> 'Futura', 'fk_brand' => 43],
                ['model'=> 'Ipanema', 'fk_brand' => 44],
                ['model'=> 'Bugato', 'fk_brand' => 44],
                ['model'=> 'Xavante XT', 'fk_brand' => 44],
                ['model'=> 'Xavante XTR', 'fk_brand' => 44],
                ['model'=> 'Xavante XTC', 'fk_brand' => 44],
                ['model'=> 'X-10', 'fk_brand' => 44],
                ['model'=> 'X-20', 'fk_brand' => 44],
                ['model'=> 'X-12', 'fk_brand' => 44],
                ['model'=> 'Tocantins', 'fk_brand' => 44],
                ['model'=> 'X-15', 'fk_brand' => 44],
                ['model'=> 'G-15', 'fk_brand' => 44],
                ['model'=> 'Itaipu E-150', 'fk_brand' => 44],
                ['model'=> 'Itaipu E-400', 'fk_brand' => 44],
                ['model'=> 'Itaipu E-500', 'fk_brand' => 44],
                ['model'=> 'G-800', 'fk_brand' => 44],
                ['model'=> 'XEF', 'fk_brand' => 44],
                ['model'=> 'Carajás', 'fk_brand' => 44],
                ['model'=> 'BR-800', 'fk_brand' => 44],
                ['model'=> 'BR-800 Van', 'fk_brand' => 44],
                ['model'=> 'Motomachine', 'fk_brand' => 44],
                ['model'=> 'Supermini', 'fk_brand' => 44],
                ['model'=> 'Hofstetter', 'fk_brand' => 44],
                ['model'=> 'Accord', 'fk_brand' => 45],
                ['model'=> 'City', 'fk_brand' => 45],
                ['model'=> 'Civic', 'fk_brand' => 45],
                ['model'=> 'Fit', 'fk_brand' => 45],
                ['model'=> 'CR-V', 'fk_brand' => 45],
                ['model'=> 'HR-V', 'fk_brand' => 45],
                ['model'=> 'WR-V', 'fk_brand' => 45],
                ['model'=> 'NSX', 'fk_brand' => 45],
                ['model'=> 'H1', 'fk_brand' => 46],
                ['model'=> 'H2', 'fk_brand' => 46],
                ['model'=> 'H3', 'fk_brand' => 46],
                ['model'=> 'Creta', 'fk_brand' => 47],
                ['model'=> 'HB20', 'fk_brand' => 47],
                ['model'=> 'HB20S', 'fk_brand' => 47],
                ['model'=> 'HB20X', 'fk_brand' => 47],
                ['model'=> 'ix20', 'fk_brand' => 47],
                ['model'=> 'ix35', 'fk_brand' => 47],
                ['model'=> 'Tucson', 'fk_brand' => 47],
                ['model'=> 'Azera', 'fk_brand' => 47],
                ['model'=> 'Veloster', 'fk_brand' => 47],
                ['model'=> 'Santa Fe', 'fk_brand' => 47],
                ['model'=> 'Veracruz', 'fk_brand' => 47],
                ['model'=> 'Genesis', 'fk_brand' => 47],
                ['model'=> 'Elantra', 'fk_brand' => 47],
                ['model'=> 'Equus', 'fk_brand' => 47],
                ['model'=> 'Sonata', 'fk_brand' => 47],
                ['model'=> 'Democrata', 'fk_brand' => 48],
                ['model'=> 'Swing', 'fk_brand' => 49],
                ['model'=> 'FX35', 'fk_brand' => 50],
                ['model'=> 'QX56', 'fk_brand' => 50],
                ['model'=> 'FX50', 'fk_brand' => 50],
                ['model'=> 'J30', 'fk_brand' => 50],
                ['model'=> 'Lassale', 'fk_brand' => 51],
                ['model'=> 'T5', 'fk_brand' => 52],
                ['model'=> 'T40', 'fk_brand' => 52],
                ['model'=> 'JAC J3', 'fk_brand' => 52],
                ['model'=> 'JAC J3 Turin', 'fk_brand' => 52],
                ['model'=> 'JAC J6', 'fk_brand' => 52],
                ['model'=> 'JAC J5', 'fk_brand' => 52],
                ['model'=> 'JAC J2', 'fk_brand' => 52],
                ['model'=> 'iEV 20', 'fk_brand' => 52],
                ['model'=> 'iEV 60', 'fk_brand' => 52],
                ['model'=> 'iEV 40', 'fk_brand' => 52],
                ['model'=> 'T80', 'fk_brand' => 52],
                ['model'=> 'T50', 'fk_brand' => 52],
                ['model'=> 'T60', 'fk_brand' => 52],
                ['model'=> 'T6', 'fk_brand' => 52],
                ['model'=> 'S-Type', 'fk_brand' => 53],
                ['model'=> 'F-Pace', 'fk_brand' => 53],
                ['model'=> 'Compass', 'fk_brand' => 54],
                ['model'=> 'Renegade', 'fk_brand' => 54],
                ['model'=> 'Cherokee', 'fk_brand' => 54],
                ['model'=> 'Grand Cherokee', 'fk_brand' => 54],
                ['model'=> 'Wrangler', 'fk_brand' => 54],
                ['model'=> 'Montez', 'fk_brand' => 55],
                ['model'=> 'Montez pick-up', 'fk_brand' => 55],
                ['model'=> 'Kia Picanto ou Kia Morning', 'fk_brand' => 56],
                ['model'=> 'Kia Cadenza ou Kia K7', 'fk_brand' => 56],
                ['model'=> 'Kia Cerato ou Kia Forte', 'fk_brand' => 56],
                ['model'=> 'Kia Cerato Koup ou Kia Koup ou Kia Forte Koup', 'fk_brand' => 56],
                ['model'=> 'Kia Sportage', 'fk_brand' => 56],
                ['model'=> 'Kia Carens ou Kia Rondo', 'fk_brand' => 56],
                ['model'=> 'Kia Sorento', 'fk_brand' => 56],
                ['model'=> 'Kia Carnival ou Kia Sedona', 'fk_brand' => 56],
                ['model'=> 'Kia Bongo', 'fk_brand' => 56],
                ['model'=> 'Kia Mohave ou Kia Borrego', 'fk_brand' => 56],
                ['model'=> 'Kia Soul', 'fk_brand' => 56],
                ['model'=> 'Kia Optima', 'fk_brand' => 56],
                ['model'=> 'Kia Quoris', 'fk_brand' => 56],
                ['model'=> 'Kia Stinger', 'fk_brand' => 56],
                ['model'=> 'Kia Rio', 'fk_brand' => 56],
                ['model'=> 'VAZ- 2105 (Laika)', 'fk_brand' => 57],
                ['model'=> 'VAZ- 2104 (Laika Station Wagon)', 'fk_brand' => 57],
                ['model'=> 'VAZ- 2108 (Samara)', 'fk_brand' => 57],
                ['model'=> 'VAZ- 2121 (Niva)', 'fk_brand' => 57],
                ['model'=> 'Ventura', 'fk_brand' => 58],
                ['model'=> 'Ventura conversível', 'fk_brand' => 58],
                ['model'=> 'Ventura II', 'fk_brand' => 58],
                ['model'=> 'Sabre', 'fk_brand' => 58],
                ['model'=> 'MP TD', 'fk_brand' => 59],
                ['model'=> 'MP LL', 'fk_brand' => 59],
                ['model'=> 'MP TI', 'fk_brand' => 59],
                ['model'=> 'MP TX', 'fk_brand' => 59],
                ['model'=> 'Range Rover Evoque', 'fk_brand' => 60],
                ['model'=> 'Range Rover', 'fk_brand' => 60],
                ['model'=> 'Range Rover Sport', 'fk_brand' => 60],
                ['model'=> 'Defender', 'fk_brand' => 60],
                ['model'=> 'Vogue', 'fk_brand' => 60],
                ['model'=> 'Autobiography', 'fk_brand' => 60],
                ['model'=> 'Range Rover Velar', 'fk_brand' => 60],
                ['model'=> 'Discovery', 'fk_brand' => 60],
                ['model'=> 'ES', 'fk_brand' => 61],
                ['model'=> 'LS', 'fk_brand' => 61],
                ['model'=> 'UX', 'fk_brand' => 61],
                ['model'=> 'NX', 'fk_brand' => 61],
                ['model'=> 'RX', 'fk_brand' => 61],
                ['model'=> 'CT', 'fk_brand' => 61],
                ['model'=> 'LC', 'fk_brand' => 61],
                ['model'=> 'NX 300h', 'fk_brand' => 61],
                ['model'=> 'Phoenix', 'fk_brand' => 62],
                ['model'=> 'Ítala', 'fk_brand' => 62],
                ['model'=> 'X60', 'fk_brand' => 63],
                ['model'=> '320', 'fk_brand' => 63],
                ['model'=> '530', 'fk_brand' => 63],
                ['model'=> 'X80', 'fk_brand' => 63],
                ['model'=> 'Continental', 'fk_brand' => 64],
                ['model'=> 'Town Car', 'fk_brand' => 64],
                ['model'=> 'H1', 'fk_brand' => 65],
                ['model'=> 'R', 'fk_brand' => 65],
                ['model'=> 'Lorena GT', 'fk_brand' => 66],
                ['model'=> 'Lorena RM', 'fk_brand' => 66],
                ['model'=> 'Lorena GT-L', 'fk_brand' => 66],
                ['model'=> 'Gurgel 1200', 'fk_brand' => 67],
                ['model'=> 'M.O.V.', 'fk_brand' => 68],
                ['model'=> 'Pick-up', 'fk_brand' => 68],
                ['model'=> 'Scorpio', 'fk_brand' => 68],
                ['model'=> 'SUV', 'fk_brand' => 68],
                ['model'=> 'Malzoni I', 'fk_brand' => 69],
                ['model'=> 'Malzoni II', 'fk_brand' => 69],
                ['model'=> 'Malzoni III', 'fk_brand' => 69],
                ['model'=> 'GT Malzoni', 'fk_brand' => 69],
                ['model'=> 'GT Malzoni II (Malzoni GTM)', 'fk_brand' => 69],
                ['model'=> 'GT Malzoni II (Malzoni GTM)', 'fk_brand' => 69],
                ['model'=> 'Matra Pick-up', 'fk_brand' => 70],
                ['model'=> '626', 'fk_brand' => 71],
                ['model'=> 'Protegè', 'fk_brand' => 71],
                ['model'=> 'MX-3', 'fk_brand' => 71],
                ['model'=> 'MX-5', 'fk_brand' => 71],
                ['model'=> 'Emme', 'fk_brand' => 72],
                ['model'=> 'Classe A', 'fk_brand' => 72],
                ['model'=> 'Classe C', 'fk_brand' => 72],
                ['model'=> 'CLC 200', 'fk_brand' => 72],
                ['model'=> 'GLA', 'fk_brand' => 72],
                ['model'=> 'CLA', 'fk_brand' => 72],
                ['model'=> 'Classe E', 'fk_brand' => 72],
                ['model'=> 'Classe S', 'fk_brand' => 72],
                ['model'=> 'GLC', 'fk_brand' => 72],
                ['model'=> 'GLE', 'fk_brand' => 72],
                ['model'=> 'GLS', 'fk_brand' => 72],
                ['model'=> 'SLC', 'fk_brand' => 72],
                ['model'=> 'Classe G', 'fk_brand' => 72],
                ['model'=> 'SLK', 'fk_brand' => 72],
                ['model'=> 'Classe GLK', 'fk_brand' => 72],
                ['model'=> 'Classe CLK', 'fk_brand' => 72],
                ['model'=> 'Classe M', 'fk_brand' => 72],
                ['model'=> 'MG550', 'fk_brand' => 73],
                ['model'=> 'MG6', 'fk_brand' => 73],
                ['model'=> 'Countryman', 'fk_brand' => 74],
                ['model'=> 'Cooper', 'fk_brand' => 74],
                ['model'=> 'Mirage GT', 'fk_brand' => 75],
                ['model'=> 'ASX', 'fk_brand' => 76],
                ['model'=> 'L200', 'fk_brand' => 76],
                ['model'=> 'Lancer', 'fk_brand' => 76],
                ['model'=> 'Pajero', 'fk_brand' => 76],
                ['model'=> 'Eclipse', 'fk_brand' => 76],
                ['model'=> 'Outlander', 'fk_brand' => 76],
                ['model'=> 'Eclipse Cross', 'fk_brand' => 76],
                ['model'=> 'Sport', 'fk_brand' => 77],
                ['model'=> 'Sport II', 'fk_brand' => 77],
                ['model'=> 'MTS', 'fk_brand' => 77],
                ['model'=> 'Targa', 'fk_brand' => 77],
                ['model'=> 'Spider', 'fk_brand' => 77],
                ['model'=> 'Kabrio', 'fk_brand' => 77],
                ['model'=> 'Saga', 'fk_brand' => 77],
                ['model'=> '787', 'fk_brand' => 77],
                ['model'=> 'X8', 'fk_brand' => 77],
                ['model'=> 'Saga II', 'fk_brand' => 77],
                ['model'=> 'Top Sport', 'fk_brand' => 77],
                ['model'=> 'X11', 'fk_brand' => 77],
                ['model'=> 'BG-Truck CD', 'fk_brand' => 77],
                ['model'=> 'Monarca', 'fk_brand' => 78],
                ['model'=> 'Jornada', 'fk_brand' => 79],
                ['model'=> 'Spirit', 'fk_brand' => 79],
                ['model'=> 'Frontier', 'fk_brand' => 80],
                ['model'=> 'Grand Livina', 'fk_brand' => 80],
                ['model'=> 'Kicks', 'fk_brand' => 80],
                ['model'=> 'Livina', 'fk_brand' => 80],
                ['model'=> 'March', 'fk_brand' => 80],
                ['model'=> 'Sentra', 'fk_brand' => 80],
                ['model'=> 'Versa', 'fk_brand' => 80],
                ['model'=> 'Leaf', 'fk_brand' => 80],
                ['model'=> 'Tiida', 'fk_brand' => 80],
                ['model'=> 'Alpini G 59 Grand Prix', 'fk_brand' => 81],
                ['model'=> '828', 'fk_brand' => 82],
                ['model'=> 'Nick', 'fk_brand' => 83],
                ['model'=> '206', 'fk_brand' => 84],
                ['model'=> '504 Pickup Diesel', 'fk_brand' => 84],
                ['model'=> '206 SW', 'fk_brand' => 84],
                ['model'=> '207', 'fk_brand' => 84],
                ['model'=> '207 Passion', 'fk_brand' => 84],
                ['model'=> '207 SW', 'fk_brand' => 84],
                ['model'=> '208', 'fk_brand' => 84],
                ['model'=> '2008', 'fk_brand' => 84],
                ['model'=> 'Hoggar', 'fk_brand' => 84],
                ['model'=> '408', 'fk_brand' => 84],
                ['model'=> '3008', 'fk_brand' => 84],
                ['model'=> '5008', 'fk_brand' => 84],
                ['model'=> '307', 'fk_brand' => 84],
                ['model'=> '405', 'fk_brand' => 84],
                ['model'=> '205', 'fk_brand' => 84],
                ['model'=> '106', 'fk_brand' => 84],
                ['model'=> '306', 'fk_brand' => 84],
                ['model'=> '406', 'fk_brand' => 84],
                ['model'=> '407', 'fk_brand' => 84],
                ['model'=> 'RCZ', 'fk_brand' => 84],
                ['model'=> 'WM II', 'fk_brand' => 85],
                ['model'=> 'Savana', 'fk_brand' => 85],
                ['model'=> 'GT (DKW) 1967 (VW)', 'fk_brand' => 86],
                ['model'=> 'GT4R', 'fk_brand' => 86],
                ['model'=> 'Puma P8', 'fk_brand' => 86],
                ['model'=> 'Puma Spyder', 'fk_brand' => 86],
                ['model'=> 'GTE', 'fk_brand' => 86],
                ['model'=> 'GTS', 'fk_brand' => 86],
                ['model'=> 'GTB', 'fk_brand' => 86],
                ['model'=> 'GTB S2', 'fk_brand' => 86],
                ['model'=> 'GTB S3', 'fk_brand' => 86],
                ['model'=> 'GTB S4', 'fk_brand' => 86],
                ['model'=> 'P-018', 'fk_brand' => 86],
                ['model'=> 'GTC', 'fk_brand' => 86],
                ['model'=> 'GTI', 'fk_brand' => 86],
                ['model'=> 'AM1', 'fk_brand' => 86],
                ['model'=> 'AM2', 'fk_brand' => 86],
                ['model'=> 'AM3', 'fk_brand' => 86],
                ['model'=> 'AM4', 'fk_brand' => 86],
                ['model'=> 'AMV', 'fk_brand' => 86],
                ['model'=> 'Puma 7900', 'fk_brand' => 86],
                ['model'=> 'Equus', 'fk_brand' => 87],
                ['model'=> 'Califórnia', 'fk_brand' => 88],
                ['model'=> 'Captur', 'fk_brand' => 89],
                ['model'=> 'Clio', 'fk_brand' => 89],
                ['model'=> 'Clio Sedan', 'fk_brand' => 89],
                ['model'=> 'Duster', 'fk_brand' => 89],
                ['model'=> 'Duster Oroch', 'fk_brand' => 89],
                ['model'=> 'Kwid', 'fk_brand' => 89],
                ['model'=> 'Logan', 'fk_brand' => 89],
                ['model'=> 'Mégane Grand Tour', 'fk_brand' => 89],
                ['model'=> 'Mégane Sedan', 'fk_brand' => 89],
                ['model'=> 'Sandero', 'fk_brand' => 89],
                ['model'=> 'Scénic', 'fk_brand' => 89],
                ['model'=> 'Fluence', 'fk_brand' => 89],
                ['model'=> 'Symbol', 'fk_brand' => 89],
                ['model'=> '19', 'fk_brand' => 89],
                ['model'=> 'Twingo', 'fk_brand' => 89],
                ['model'=> 'Zoe', 'fk_brand' => 89],
                ['model'=> 'Twizy', 'fk_brand' => 89],
                ['model'=> 'Isetta', 'fk_brand' => 90],
                ['model'=> '9000', 'fk_brand' => 91],
                ['model'=> 'Alvorada', 'fk_brand' => 92],
                ['model'=> 'Chambord', 'fk_brand' => 92],
                ['model'=> 'Emi-Sul', 'fk_brand' => 92],
                ['model'=> 'Esplanada', 'fk_brand' => 92],
                ['model'=> 'GTX', 'fk_brand' => 92],
                ['model'=> 'Jangada', 'fk_brand' => 92],
                ['model'=> 'Presidence', 'fk_brand' => 92],
                ['model'=> 'Rally', 'fk_brand' => 92],
                ['model'=> 'Regente', 'fk_brand' => 92],
                ['model'=> 'Tufão', 'fk_brand' => 92],
                ['model'=> 'SM Hatch', 'fk_brand' => 93],
                ['model'=> 'SM Conversível', 'fk_brand' => 93],
                ['model'=> 'SM Coupé', 'fk_brand' => 93],
                ['model'=> 'San Vito', 'fk_brand' => 94],
                ['model'=> 'Córdoba', 'fk_brand' => 95],
                ['model'=> 'Ibiza', 'fk_brand' => 95],
                ['model'=> 'Inca', 'fk_brand' => 95],
                ['model'=> 'Vario', 'fk_brand' => 95],
                ['model'=> 'Fortwo', 'fk_brand' => 96],
                ['model'=> 'Uirapuru berlineta', 'fk_brand' => 97],
                ['model'=> 'Uirapuru cabriolet', 'fk_brand' => 97],
                ['model'=> 'Gringo', 'fk_brand' => 98],
                ['model'=> 'Ibiza', 'fk_brand' => 99],
                ['model'=> 'Max Sport', 'fk_brand' => 99],
                ['model'=> 'Max Sport 2', 'fk_brand' => 99],
                ['model'=> 'Deserter 2', 'fk_brand' => 99],
                ['model'=> 'Deserter Rally', 'fk_brand' => 99],
                ['model'=> 'Deserter XK', 'fk_brand' => 99],
                ['model'=> 'Country XK', 'fk_brand' => 99],
                ['model'=> 'Impreza', 'fk_brand' => 100],
                ['model'=> 'Forester', 'fk_brand' => 100],
                ['model'=> 'WRX', 'fk_brand' => 100],
                ['model'=> 'Outback', 'fk_brand' => 100],
                ['model'=> 'XV', 'fk_brand' => 100],
                ['model'=> 'Legacy', 'fk_brand' => 100],
                ['model'=> 'Jimny', 'fk_brand' => 101],
                ['model'=> 'Grand Vitara', 'fk_brand' => 101],
                ['model'=> 'Vitara', 'fk_brand' => 101],
                ['model'=> 'Suzuki SX4 S-Cross', 'fk_brand' => 101],
                ['model'=> 'XLV', 'fk_brand' => 102],
                ['model'=> 'Tivoli', 'fk_brand' => 102],
                ['model'=> 'Actyon', 'fk_brand' => 102],
                ['model'=> 'Actyon Sports', 'fk_brand' => 102],
                ['model'=> 'Korando', 'fk_brand' => 102],
                ['model'=> 'Kyron', 'fk_brand' => 102],
                ['model'=> 'Rexton', 'fk_brand' => 102],
                ['model'=> 'Stark', 'fk_brand' => 103],
                ['model'=> 'Lucena', 'fk_brand' => 104],
                ['model'=> 'Bandeirante', 'fk_brand' => 105],
                ['model'=> 'Camry', 'fk_brand' => 105],
                ['model'=> 'Corolla', 'fk_brand' => 105],
                ['model'=> 'Etios', 'fk_brand' => 105],
                ['model'=> 'Fielder', 'fk_brand' => 105],
                ['model'=> 'Hilux', 'fk_brand' => 105],
                ['model'=> 'Prius', 'fk_brand' => 105],
                ['model'=> 'RAV4', 'fk_brand' => 105],
                ['model'=> 'SW4', 'fk_brand' => 105],
                ['model'=> 'Yaris', 'fk_brand' => 105],
                ['model'=> 'Previa', 'fk_brand' => 105],
                ['model'=> 'Audax', 'fk_brand' => 106],
                ['model'=> 'Pantanal', 'fk_brand' => 107],
                ['model'=> 'T4', 'fk_brand' => 107],
                ['model'=> 'Villa GT', 'fk_brand' => 108],
                ['model'=> 'XC40', 'fk_brand' => 108],
                ['model'=> 'XC60', 'fk_brand' => 108],
                ['model'=> 'XC90', 'fk_brand' => 108],
                ['model'=> 'V40', 'fk_brand' => 108],
                ['model'=> 'V60', 'fk_brand' => 108],
                ['model'=> 'S60', 'fk_brand' => 108],
                ['model'=> 'S90', 'fk_brand' => 108],
                ['model'=> '850', 'fk_brand' => 108],
                ['model'=> 'C30', 'fk_brand' => 108],
                ['model'=> 'V50', 'fk_brand' => 108],
                ['model'=> 'XC70', 'fk_brand' => 108],
                ['model'=> 'V50', 'fk_brand' => 108],
                ['model'=> 'C70', 'fk_brand' => 108],
                ['model'=> '1600', 'fk_brand' => 109],
                ['model'=> 'Apollo', 'fk_brand' => 109],
                ['model'=> 'Amarok', 'fk_brand' => 109],
                ['model'=> 'Brasília', 'fk_brand' => 109],
                ['model'=> 'Fox', 'fk_brand' => 109],
                ['model'=> 'Fusca', 'fk_brand' => 109],
                ['model'=> 'Gol', 'fk_brand' => 109],
                ['model'=> 'Golf', 'fk_brand' => 109],
                ['model'=> 'Jetta', 'fk_brand' => 109],
                ['model'=> 'Karmann Ghia', 'fk_brand' => 109],
                ['model'=> 'Karmann Ghia Cabriolet', 'fk_brand' => 109],
                ['model'=> 'Karmann Ghia TC', 'fk_brand' => 109],
                ['model'=> 'Kombi', 'fk_brand' => 109],
                ['model'=> 'Logus', 'fk_brand' => 109],
                ['model'=> 'Parati', 'fk_brand' => 109],
                ['model'=> 'Passat', 'fk_brand' => 109],
                ['model'=> 'Pointer', 'fk_brand' => 109],
                ['model'=> 'Polo', 'fk_brand' => 109],
                ['model'=> 'Polo Classic', 'fk_brand' => 109],
                ['model'=> 'Polo Sedan', 'fk_brand' => 109],
                ['model'=> 'Quantum', 'fk_brand' => 109],
                ['model'=> 'Santana', 'fk_brand' => 109],
                ['model'=> 'Saveiro', 'fk_brand' => 109],
                ['model'=> 'SP1', 'fk_brand' => 109],
                ['model'=> 'SP2', 'fk_brand' => 109],
                ['model'=> 'TL', 'fk_brand' => 109],
                ['model'=> 'Up!', 'fk_brand' => 109],
                ['model'=> 'Variant', 'fk_brand' => 109],
                ['model'=> 'Variant II', 'fk_brand' => 109],
                ['model'=> 'Virtus', 'fk_brand' => 109],
                ['model'=> 'Voyage', 'fk_brand' => 109],
                ['model'=> 'Bora', 'fk_brand' => 109],
                ['model'=> 'T-Cross', 'fk_brand' => 109],
                ['model'=> 'Tiguan', 'fk_brand' => 109],
                ['model'=> 'Touareg', 'fk_brand' => 109],
                ['model'=> 'WMV', 'fk_brand' => 110],
                ['model'=> '1093', 'fk_brand' => 111],
                ['model'=> 'Aero', 'fk_brand' => 111],
                ['model'=> 'Dauphine', 'fk_brand' => 111],
                ['model'=> 'Gordini', 'fk_brand' => 111],
                ['model'=> 'Interlagos', 'fk_brand' => 111],
                ['model'=> 'Itamaraty', 'fk_brand' => 111],
                ['model'=> 'Itamaraty Executivo', 'fk_brand' => 111],
                ['model'=> 'Jeep CJ-5', 'fk_brand' => 111],
                ['model'=> 'Jeep CJ-6', 'fk_brand' => 111],
                ['model'=> 'Jeep pick-up', 'fk_brand' => 111],
                ['model'=> 'Rural', 'fk_brand' => 111],
                ['model'=> 'Teimoso', 'fk_brand' => 111],
                ['model'=> 'Capeta', 'fk_brand' => 111]
                
            )
        );

    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('models');
    }
}
